---
- hosts: localhost
  become: true
  vars:
    bucket_name: sample-vishu3452
    state: present
    access_key: 
    aws_secret: 
    aws_region: ap-south-1

  tasks:
    - name: Install boto3
      pip:
        name: boto3
        state: present
    - name: Create S3 bucket
      s3_bucket: 
        name: "{{ bucket_name }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ aws_secret }}"
        state: "{{ state }}"
        region: "{{ aws_region }}"


    # - name: Set AWS KEY ID
    #   set_fact: aws_key_id="{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    #   delegate_to: 127.0.0.1
    # - name: Set AWS SECRET
    #   set_fact: aws_secret_key="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    #   delegate_to: 127.0.0.1
    # - name: Get AWS KEY ID
    #   set_fact: aws_key_id={{hostvars[inventory_hostname]['aws_key_id']}}
    # - name: Get AWS SECRET KEY
    #   set_fact: aws_secret_key={{hostvars[inventory_hostname]['aws_secret_key']}}