---
- hosts: localhost
  # vars:
  #   project_dir: "./"
  #   state: present #planned, absent
  #   s3_bucket: sample-vishu135
  #   key: terraform.tfstate
  #   aws_region: ap-south-1
  #   app_env: dev
  vars_files:
    - ./vars/external_vars.yaml
  tasks:
    - name: Run Terraform scripts
      terraform:
        project_path: "{{ project_dir }}"
        state: "{{ state }}"
        force_init: true
        backend_config:
          bucket: "{{ s3_bucket }}"
          key: "{{ key }}"
          region: "{{ aws_region }}"
        #state_file: random.tfstate --> It is used only when state has planned value

#ansible-playbook terraform.yaml -e app_env=dev (or) --extra-vars "app_env=dev aws_region=ap-south-1" 
